"""create onboarding tables

Revision ID: 6258af572075
Revises: 
Create Date: 2025-09-01 04:39:07.388868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6258af572075'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboard_quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboard_quest_id'), 'onboard_quest', ['id'], unique=False)
    op.create_index(op.f('ix_onboard_quest_question_id'), 'onboard_quest', ['question_id'], unique=False)
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('referral', sa.String(), nullable=False),
    sa.Column('onboarding_query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_id'), 'user_info', ['id'], unique=False)
    op.create_index(op.f('ix_user_info_usid'), 'user_info', ['usid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_usid'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_id'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_onboard_quest_question_id'), table_name='onboard_quest')
    op.drop_index(op.f('ix_onboard_quest_id'), table_name='onboard_quest')
    op.drop_table('onboard_quest')
    # ### end Alembic commands ###
