"""initial schema

Revision ID: a7300fc42c26
Revises: 
Create Date: 2025-08-28 22:35:05.046021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7300fc42c26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboard_quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_index(op.f('ix_onboard_quest_id'), 'onboard_quest', ['id'], unique=False)
    op.create_table('user_info',
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('q1', sa.String(), nullable=False),
    sa.Column('q2', sa.String(), nullable=False),
    sa.Column('q3', sa.String(), nullable=False),
    sa.Column('q4', sa.String(), nullable=False),
    sa.Column('q5', sa.String(), nullable=False),
    sa.Column('q6', sa.String(), nullable=False),
    sa.Column('q7', sa.String(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('usid')
    )
    op.create_index(op.f('ix_user_info_usid'), 'user_info', ['usid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_usid'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_onboard_quest_id'), table_name='onboard_quest')
    op.drop_table('onboard_quest')
    # ### end Alembic commands ###
