"""Create initial tables

Revision ID: 4e17e47ab352
Revises: 
Create Date: 2025-08-26 06:00:56.508829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e17e47ab352'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_questionnaire_id'), 'onboarding_questionnaire', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_questionnaire_question'), 'onboarding_questionnaire', ['question'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_info',
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('q1', sa.String(), nullable=True),
    sa.Column('q2', sa.String(), nullable=True),
    sa.Column('q3', sa.String(), nullable=True),
    sa.Column('q4', sa.String(), nullable=True),
    sa.Column('q5', sa.String(), nullable=True),
    sa.Column('q6', sa.String(), nullable=True),
    sa.Column('q7', sa.String(), nullable=True),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('usid')
    )
    op.create_index(op.f('ix_user_info_usid'), 'user_info', ['usid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_usid'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_onboarding_questionnaire_question'), table_name='onboarding_questionnaire')
    op.drop_index(op.f('ix_onboarding_questionnaire_id'), table_name='onboarding_questionnaire')
    op.drop_table('onboarding_questionnaire')
    # ### end Alembic commands ###
